### ISSUE TITLE
Restarts Every Day at Midnight

### ISSUE THREAD

**Issue by anndrewww** [npetrovski/yi-hack-easy#1]
Restarts everyday at midnight with loud voice startup

**Comment by npetrovski** [comment]
True, and this is expected. There is a cronjob running, which does a camera restart at midnight. 

This can be changed from `crontab.cfg` file - just remove the first line:

`0 0 * * * /sbin/reboot`

and no restart should happen every day at 00:00. Also, instead of removing this line you can simply change the frequency of the restart - see [https://en.wikipedia.org/wiki/Cron](https://en.wikipedia.org/wiki/Cron)
